#' @title Validate CrossRef Publications
#' @description Given a \code{data.frame()} of publication information, and a set of publications, allow interactive selection of "best matches" for publications.
#' @param cross A list generated by the function \code{scrape_dois()}.
#' @param pubs A \code{data.frame()} from the users (unformatted) publication data.
#' @param results The match values returned from \code{scrape_dois()}.
#' @export
matchPubs <- function(cross, pubs, results) {
  bestMatch <- list()

  for(i in 1:length(cross)) {
    bestMatch[[i]] <- findMatch(pubs[i],
                                results[[i]],
                                cross[[i]])
    if (!('publication' %in% class(bestMatch[[i]]) | suppressWarnings(is.na(bestMatch[[i]])))) {
      bestMatch[[i]] <- NULL
      break
    }
  }
  return(bestMatch)
}
